from app.v2.config.models import IssueTaxonomyEntry


ISSUE_TAXONOMY: list[IssueTaxonomyEntry] = [
    IssueTaxonomyEntry(
        code="FINANCE_VISIBILITY_GAP",
        label="Financial visibility is too weak for confident decisions",
        description="Cash visibility and reporting rhythm are not strong enough for predictable decisions.",
        section_key="financial_control_cash_discipline",
        severity="high",
        action_family_codes=["FINANCIAL_CONTROL", "METRIC_VISIBILITY"],
    ),
    IssueTaxonomyEntry(
        code="REACTIVE_CASH_MANAGEMENT",
        label="Cash management is still reactive",
        description="Short-term cash pressure is being handled too late and with too little control.",
        section_key="financial_control_cash_discipline",
        severity="critical",
        action_family_codes=["FINANCIAL_CONTROL", "ACCOUNTABILITY_RHYTHMS"],
    ),
    IssueTaxonomyEntry(
        code="OVERDUE_RECEIVABLES_TRAP",
        label="Collections and receivables are draining cash confidence",
        description="Overdue balances or weak follow-up are turning sales into delayed cash flow.",
        section_key="financial_control_cash_discipline",
        severity="high",
        action_family_codes=["FINANCIAL_CONTROL", "METRIC_VISIBILITY"],
    ),
    IssueTaxonomyEntry(
        code="DELIVERY_UNRELIABILITY",
        label="Delivery reliability is too fragile",
        description="Delays, rework, or missed commitments are undermining operating confidence.",
        section_key="operations_delivery_reliability",
        severity="high",
        action_family_codes=["PROCESS_STANDARDIZATION", "ACCOUNTABILITY_RHYTHMS"],
    ),
    IssueTaxonomyEntry(
        code="OPERATIONS_VISIBILITY_GAP",
        label="Operations issues are not visible early enough",
        description="The team cannot see operating slippage quickly enough to intervene early.",
        section_key="operations_delivery_reliability",
        severity="medium",
        action_family_codes=["METRIC_VISIBILITY", "ACCOUNTABILITY_RHYTHMS"],
    ),
    IssueTaxonomyEntry(
        code="HIGH_COMPLAINT_SERVICE_BREAKDOWN",
        label="Customer service quality is breaking down too often",
        description="Inconsistent follow-up or weak complaint visibility is hurting retention and trust.",
        section_key="customer_retention_service_quality",
        severity="high",
        action_family_codes=["CUSTOMER_LOOP", "METRIC_VISIBILITY"],
    ),
    IssueTaxonomyEntry(
        code="SALES_PIPELINE_WEAKNESS",
        label="Sales execution is not reliably repeatable",
        description="Lead handling and conversion are still inconsistent and hard to forecast.",
        section_key="revenue_engine",
        severity="high",
        action_family_codes=["PIPELINE_DISCIPLINE", "METRIC_VISIBILITY"],
    ),
    IssueTaxonomyEntry(
        code="MANAGEMENT_VISIBILITY_GAP",
        label="Management control and review rhythms are too weak",
        description="Priorities, review cadence, or decision visibility are not strong enough to steer execution.",
        section_key="management_control_planning_discipline",
        severity="high",
        action_family_codes=["ACCOUNTABILITY_RHYTHMS", "METRIC_VISIBILITY"],
    ),
    IssueTaxonomyEntry(
        code="TEAM_CONTINUITY_RISK",
        label="Team continuity is exposed by role dependency",
        description="Knowledge coverage and handoffs are too fragile for stable execution.",
        section_key="team_capacity_continuity",
        severity="medium",
        action_family_codes=["PROCESS_STANDARDIZATION", "ACCOUNTABILITY_RHYTHMS"],
    ),
    IssueTaxonomyEntry(
        code="MARKET_OFFER_GAP",
        label="The offer is not clear enough to the market",
        description="The business still lacks enough offer clarity to support consistent growth.",
        section_key="market_offer_strength",
        severity="medium",
        action_family_codes=["PIPELINE_DISCIPLINE", "EXECUTION_FOCUS"],
    ),
    IssueTaxonomyEntry(
        code="GROWTH_BLOCKER_UNRESOLVED",
        label="A major growth blocker is unresolved",
        description="A known constraint is still limiting throughput, growth, or consistency.",
        section_key="revenue_engine",
        severity="high",
        action_family_codes=["CONSTRAINT_REMOVAL", "EXECUTION_FOCUS"],
    ),
]
