from app.v2.config.models import AdaptiveModuleDefinition, QuestionDefinition


ADAPTIVE_MODULE_REGISTRY: list[AdaptiveModuleDefinition] = [
    AdaptiveModuleDefinition(
        key="inventory_stock_control",
        label="Inventory & Stock Control",
        description="Questions for businesses where stock accuracy and replenishment materially affect outcomes.",
        trigger_type="profile_field",
        trigger_field="primary_business_type",
        trigger_values=["retail", "food_and_hospitality"],
        parent_section_key="operations_delivery_reliability",
        questions=[
            QuestionDefinition(
                key="inventory_accuracy_visibility",
                prompt="How accurate and trusted is your current stock visibility?",
                input_type="select",
                scale_key="coverage_4",
                essential=True,
                scored=True,
                bucket="control",
                allow_unknown=True,
                tags=["inventory", "stock"],
            ),
            QuestionDefinition(
                key="inventory_stock_issue_notes",
                prompt="What most often causes stockouts, overstock, or shrinkage?",
                input_type="textarea",
                scale_key="free_text",
                essential=False,
                scored=False,
                bucket="risk",
                allow_unknown=True,
                interpretation_enabled=True,
                max_length=1500,
                tags=["inventory", "root_cause"],
            ),
        ],
    ),
    AdaptiveModuleDefinition(
        key="service_capacity_scheduling",
        label="Service Capacity & Scheduling",
        description="Questions for service-led businesses managing demand, scheduling, and delivery load.",
        trigger_type="profile_field",
        trigger_field="primary_business_type",
        trigger_values=["services"],
        parent_section_key="operations_delivery_reliability",
        questions=[
            QuestionDefinition(
                key="service_capacity_planning",
                prompt="How well can you plan workload before accepting more service demand?",
                input_type="select",
                scale_key="maturity_4",
                essential=True,
                scored=True,
                bucket="control",
                allow_unknown=True,
                tags=["service", "capacity"],
            ),
            QuestionDefinition(
                key="service_scheduling_breakdown_notes",
                prompt="What most often causes service scheduling conflicts, overload, or delays?",
                input_type="textarea",
                scale_key="free_text",
                essential=False,
                scored=False,
                bucket="risk",
                allow_unknown=True,
                interpretation_enabled=True,
                max_length=1500,
                tags=["service", "scheduling"],
            ),
        ],
    ),
    AdaptiveModuleDefinition(
        key="production_process_reliability",
        label="Production / Process Reliability",
        description="Questions for businesses with production or process throughput dependence.",
        trigger_type="profile_field",
        trigger_field="primary_business_type",
        trigger_values=["manufacturing"],
        parent_section_key="operations_delivery_reliability",
        questions=[
            QuestionDefinition(
                key="production_flow_stability",
                prompt="How stable is the production or processing flow needed to meet demand?",
                input_type="select",
                scale_key="maturity_4",
                essential=True,
                scored=True,
                bucket="outcome",
                allow_unknown=True,
                tags=["production", "throughput"],
            ),
            QuestionDefinition(
                key="production_failure_notes",
                prompt="What most often causes production disruption, defects, or rework?",
                input_type="textarea",
                scale_key="free_text",
                essential=False,
                scored=False,
                bucket="risk",
                allow_unknown=True,
                interpretation_enabled=True,
                max_length=1500,
                tags=["production", "root_cause"],
            ),
        ],
    ),
    AdaptiveModuleDefinition(
        key="credit_collections",
        label="Credit & Collections",
        description="Questions for businesses materially exposed to delayed collections or receivables risk.",
        trigger_type="profile_field",
        trigger_field="credit_sales_exposure",
        trigger_values=["moderate", "high"],
        parent_section_key="financial_control_cash_discipline",
        questions=[
            QuestionDefinition(
                key="collections_follow_up_visibility",
                prompt="How visible are overdue balances and the status of collection follow-up?",
                input_type="select",
                scale_key="coverage_4",
                essential=True,
                scored=True,
                bucket="control",
                allow_unknown=True,
                tags=["collections", "cash"],
            ),
            QuestionDefinition(
                key="collections_delay_notes",
                prompt="What most often delays payment collection?",
                input_type="textarea",
                scale_key="free_text",
                essential=False,
                scored=False,
                bucket="risk",
                allow_unknown=True,
                interpretation_enabled=True,
                max_length=1500,
                tags=["collections", "receivables"],
            ),
        ],
    ),
]
