from app.v2.config.models import QuestionDefinition, SectionDefinition


CORE_SECTION_REGISTRY: list[SectionDefinition] = [
    SectionDefinition(
        key="market_offer_strength",
        label="Market & Offer Strength",
        description="How clearly the offer matches market demand and customer needs.",
        order=1,
        questions=[
            QuestionDefinition(
                key="market_offer_clarity",
                prompt="How clearly is your main offer defined for your target customer?",
                input_type="select",
                scale_key="maturity_4",
                essential=True,
                scored=True,
                bucket="outcome",
                allow_unknown=True,
                help_text="Think about whether the team can explain the main offer consistently.",
                tags=["offer", "positioning"],
            ),
            QuestionDefinition(
                key="market_customer_signal_sources",
                prompt="Which channels currently give you the clearest signals about customer demand?",
                input_type="multiselect",
                scale_key="business_channel_mix",
                essential=False,
                scored=False,
                bucket="control",
                allow_unknown=True,
                multi_select_max_items=4,
                tags=["demand_signal", "channels"],
            ),
            QuestionDefinition(
                key="market_offer_shift_notes",
                prompt="What has changed most recently in customer demand for your offer?",
                input_type="textarea",
                scale_key="free_text",
                essential=False,
                scored=False,
                bucket="risk",
                allow_unknown=True,
                interpretation_enabled=True,
                max_length=1500,
                tags=["market_change", "interpretation"],
            ),
        ],
    ),
    SectionDefinition(
        key="revenue_engine",
        label="Revenue Engine",
        description="How predictably the business turns activity into sales and collected revenue.",
        order=2,
        questions=[
            QuestionDefinition(
                key="revenue_sales_pipeline_repeatability",
                prompt="How repeatable is the path from lead or customer interest to completed sale?",
                input_type="select",
                scale_key="maturity_4",
                essential=True,
                scored=True,
                bucket="control",
                allow_unknown=True,
                tags=["pipeline", "conversion"],
            ),
            QuestionDefinition(
                key="revenue_target_confidence",
                prompt="On a scale of 0 to 10, how confident are you in next month’s revenue outcome?",
                input_type="number",
                scale_key="numeric_0_10",
                essential=True,
                scored=True,
                bucket="outcome",
                allow_unknown=True,
                tags=["forecasting", "confidence"],
            ),
            QuestionDefinition(
                key="revenue_constraint_notes",
                prompt="What most often disrupts or slows revenue generation?",
                input_type="textarea",
                scale_key="free_text",
                essential=False,
                scored=False,
                bucket="risk",
                allow_unknown=True,
                interpretation_enabled=True,
                max_length=1500,
                tags=["constraint", "root_cause"],
            ),
        ],
    ),
    SectionDefinition(
        key="customer_retention_service_quality",
        label="Customer Retention & Service Quality",
        description="How well the business keeps customers returning and maintains service quality.",
        order=3,
        questions=[
            QuestionDefinition(
                key="customer_follow_up_consistency",
                prompt="How consistently do you follow up after a sale or service interaction?",
                input_type="select",
                scale_key="frequency_4",
                essential=True,
                scored=True,
                bucket="outcome",
                allow_unknown=True,
                tags=["retention", "follow_up"],
            ),
            QuestionDefinition(
                key="customer_service_issue_visibility",
                prompt="How visible are recurring customer complaints or service-quality issues?",
                input_type="select",
                scale_key="coverage_4",
                essential=True,
                scored=True,
                bucket="control",
                allow_unknown=True,
                tags=["quality", "visibility"],
            ),
            QuestionDefinition(
                key="customer_quality_notes",
                prompt="Where does service quality or customer retention break down most often?",
                input_type="textarea",
                scale_key="free_text",
                essential=False,
                scored=False,
                bucket="risk",
                allow_unknown=True,
                interpretation_enabled=True,
                max_length=1500,
                tags=["quality", "retention"],
            ),
        ],
    ),
    SectionDefinition(
        key="financial_control_cash_discipline",
        label="Financial Control & Cash Discipline",
        description="How well the business tracks cash, reporting cadence, and financial surprises.",
        order=4,
        questions=[
            QuestionDefinition(
                key="finance_reporting_rhythm",
                prompt="How regularly do you review the core numbers needed to run the business?",
                input_type="select",
                scale_key="frequency_4",
                essential=True,
                scored=True,
                bucket="control",
                allow_unknown=True,
                tags=["reporting", "control"],
            ),
            QuestionDefinition(
                key="finance_cash_position_clarity",
                prompt="On a scale of 0 to 10, how clearly can you see short-term cash position?",
                input_type="number",
                scale_key="numeric_0_10",
                essential=True,
                scored=True,
                bucket="outcome",
                allow_unknown=True,
                tags=["cash", "visibility"],
            ),
            QuestionDefinition(
                key="finance_surprise_notes",
                prompt="What kinds of cash or reporting surprises still catch the business off guard?",
                input_type="textarea",
                scale_key="free_text",
                essential=False,
                scored=False,
                bucket="risk",
                allow_unknown=True,
                interpretation_enabled=True,
                max_length=1500,
                tags=["risk", "cash"],
            ),
        ],
    ),
    SectionDefinition(
        key="operations_delivery_reliability",
        label="Operations & Delivery Reliability",
        description="How consistently work is executed, delivered, and tracked.",
        order=5,
        questions=[
            QuestionDefinition(
                key="operations_process_stability",
                prompt="How stable and repeatable are the key operating steps needed to deliver your offer?",
                input_type="select",
                scale_key="maturity_4",
                essential=True,
                scored=True,
                bucket="control",
                allow_unknown=True,
                tags=["operations", "repeatability"],
            ),
            QuestionDefinition(
                key="operations_issue_visibility",
                prompt="How quickly do operating delays or delivery issues become visible to the team?",
                input_type="select",
                scale_key="coverage_4",
                essential=True,
                scored=True,
                bucket="outcome",
                allow_unknown=True,
                tags=["delivery", "visibility"],
            ),
            QuestionDefinition(
                key="operations_reliability_notes",
                prompt="What most often causes delays, rework, or missed commitments?",
                input_type="textarea",
                scale_key="free_text",
                essential=False,
                scored=False,
                bucket="risk",
                allow_unknown=True,
                interpretation_enabled=True,
                max_length=1500,
                tags=["delivery", "root_cause"],
            ),
        ],
    ),
    SectionDefinition(
        key="management_control_planning_discipline",
        label="Management Control & Planning Discipline",
        description="How well priorities, review rhythms, and decision-making are managed.",
        order=6,
        questions=[
            QuestionDefinition(
                key="management_priority_clarity",
                prompt="How clearly are the business’s current priorities defined and reviewed?",
                input_type="select",
                scale_key="maturity_4",
                essential=True,
                scored=True,
                bucket="control",
                allow_unknown=True,
                tags=["planning", "priorities"],
            ),
            QuestionDefinition(
                key="management_decision_data_quality",
                prompt="How usable is the information you rely on for weekly decisions?",
                input_type="select",
                scale_key="coverage_4",
                essential=True,
                scored=True,
                bucket="outcome",
                allow_unknown=True,
                tags=["management", "data"],
            ),
            QuestionDefinition(
                key="management_control_notes",
                prompt="Where does planning discipline or management control still break down?",
                input_type="textarea",
                scale_key="free_text",
                essential=False,
                scored=False,
                bucket="risk",
                allow_unknown=True,
                interpretation_enabled=True,
                max_length=1500,
                tags=["planning", "control"],
            ),
        ],
    ),
    SectionDefinition(
        key="team_capacity_continuity",
        label="Team Capacity & Continuity",
        description="How resilient the team is to handoff issues, overload, and single-person dependency.",
        order=7,
        questions=[
            QuestionDefinition(
                key="team_role_coverage",
                prompt="How clear is role coverage for the work that keeps the business running?",
                input_type="select",
                scale_key="maturity_4",
                essential=True,
                scored=True,
                bucket="control",
                allow_unknown=True,
                tags=["team", "roles"],
            ),
            QuestionDefinition(
                key="team_single_point_dependency",
                prompt="Is the business heavily dependent on one person for critical knowledge or approvals?",
                input_type="select",
                scale_key="yes_no",
                essential=True,
                scored=True,
                bucket="risk",
                allow_unknown=True,
                tags=["continuity", "dependency"],
            ),
            QuestionDefinition(
                key="team_capacity_notes",
                prompt="Where does team capacity or continuity feel most fragile today?",
                input_type="textarea",
                scale_key="free_text",
                essential=False,
                scored=False,
                bucket="risk",
                allow_unknown=True,
                interpretation_enabled=True,
                max_length=1500,
                tags=["team", "continuity"],
            ),
        ],
    ),
    SectionDefinition(
        key="critical_risk_checks",
        label="Critical Risk Checks",
        description="Short checks for material risks that may require fast follow-up later.",
        order=8,
        questions=[
            QuestionDefinition(
                key="risk_cash_pressure_check",
                prompt="Have you experienced recent cash pressure that could disrupt normal operations?",
                input_type="select",
                scale_key="yes_no",
                essential=True,
                scored=False,
                bucket="risk",
                allow_unknown=True,
                tags=["critical_risk", "cash"],
            ),
            QuestionDefinition(
                key="risk_compliance_exposure_check",
                prompt="Are there compliance obligations where a missed step could materially affect the business?",
                input_type="select",
                scale_key="yes_no",
                essential=True,
                scored=False,
                bucket="risk",
                allow_unknown=True,
                allow_prefer_not_to_say=True,
                tags=["critical_risk", "compliance"],
            ),
            QuestionDefinition(
                key="risk_other_critical_notes",
                prompt="What other critical risk feels most urgent right now?",
                input_type="textarea",
                scale_key="free_text",
                essential=False,
                scored=False,
                bucket="risk",
                allow_unknown=True,
                allow_prefer_not_to_say=True,
                interpretation_enabled=True,
                max_length=1500,
                tags=["critical_risk", "interpretation"],
            ),
        ],
    ),
]
